{
	Language= [
		{
			"LoadSet": "負載設定",
			"TableW": "工作台重量(kg)",
			"WpW": "工作物重量(kg)",
			"u": "摩擦係數",
			"AF": "軸向負荷(kg)",
			"MaxV": "最高進給速度(m/min)",
			"MaxRpm": "馬達最高轉速(rpm)",
			"MinLead": "最小導程(mm)",
			"ChooseLead": "選用導程(mm)",
			"RunSet": "運轉條件",
			"G0L": "快送進給阻力(kg)",
			"G0F": "快送進給速度(mm/min)",
			"G0T": "快送進給比例(%)",
			"G1L": "輕中切削阻力(kg)",
			"G1F": "輕中切削進給速度(mm/min)",
			"G1T": "輕中切削比例(%)",
			"G2L": "重切削阻力(kg)",
			"G2F": "重切削進給速度(mm/min)",
			"G2T": "重切削比例(%)",
			"MeanL": "平均負荷(kgf)",
			"MeanRpm": "平均轉速(rpm)",
			"BasicDload": "額定動負荷計算",
			"Rlife": "要求壽命(hr)",
			"SafeC": "負荷係數",
			"MinLoad": "最低動負荷(kgf)",
			"ScrewDset": "軸徑選定",
			"MaxStork": "最大行程(mm)",
			"NutL": "螺帽長度(mm)",
			"Unthread": "軸端預留量(mm)",
			"Shaftmount": "安裝方式",
			"MinD": "最小螺桿根徑(mm)",
			"SupSup": "支持-支持",
			"FixSup": "固定-支持",
			"FixFix": "固定-固定",
			"FixFree": "固定-自由",
			"NutSet": "螺帽選定",
			"Flangetype": "法蘭型式",
			"Nutype": "螺帽型式",
			"CirculType": "循環方式",
			"Choosenut": "螺帽型式",
			"Suggestod": "螺桿外徑",
			"Suggestlead": "導程",
			"BD": "鋼珠直徑",
			"ET": "循環圈數",
			"Suggestca": "動負荷(kg)",
			"Sload": "靜負荷(kg)",
			"NutOD": "帽徑(mm)",
			"NutLen": "帽長(mm)",
			"LifeCal": "壽命計算",
			"NutDynamic": "螺帽動負荷(kgf)",
			"Mrpm": "平均轉速(rpm)",
			"Mload": "平均負荷",
			"SO": "負荷係數",
			"LifeP": "壽命預測(hr)",
			"LifeR": "壽命結果",
			"CS": "選用螺桿直徑(mm)",
			"Drpm": "危險轉速(rpm)",
			"RpmR": "轉速符合",
			"Pstep": "上一步",
			"Nstep": "下一步"
		},
		{
			"LoadSet": "LoadSetting",
			"TableW": "Table weight(kg)",
			"WpW": "Work-piece weight(kg)",
			"u": "Friction coefficient",
			"AF": "Axial force(kg)",
			"MaxV": "MaxFeedrate(m/min)",
			"MaxRpm": "MaxRpm",
			"MinLead": "MinLead(mm)",
			"ChooseLead": "ChooseLead(mm)",
			"RunSet": "RunSetting",
			"G0L": "RapidFeedResistance(kg)",
			"G0F": "RapidFeedSpeed(mm/min)",
			"G0T": "RapidFeedTime(%)",
			"G1L": "LightFeedResistance(kg)",
			"G1F": "LightFeedSpeed(mm/min)",
			"G1T": "LightFeedTime(%)",
			"G2L": "HeavyFeedResistance(kg)",
			"G2F": "HeavyFeedSpeed(mm/min)",
			"G2T": "HeavyFeedTime(%)",
			"MeanL": "MeanLoad(kgf)",
			"MeanRpm": "MeanRotation(rpm)",
			"BasicDload": "Basic dynamic rate load",
			"Rlife": "RequireLife(hr)",
			"SafeC": "Safe coefficient",
			"MinLoad": "Min dynamic rate load(kgf)",
			"ScrewDset": " Screw shaft diameter",
			"MaxStork": "MaxStork(mm)",
			"NutL": "NutLength(mm)",
			"Unthread": " Unthread area length(mm)",
			"Shaftmount": "Shaft mounting method",
			"MinD": "Min shaft diameter(mm)",
			"SupSup": "Supported-Supported",
			"FixSup": "Fixed-Supported",
			"FixFix": "Fixed-Fixed",
			"FixFree": "Fixed-Free",
			"NutSet": "Type of nut selecting",
			"Flangetype": "Flange type",
			"Nutype": "Nut type",
			"CirculType": "Circulation type",
			"Choosenut": "Nut type",
			"Suggestod": "Screw O.D.",
			"Suggestlead": "Lead",
			"BD": "Ball diameter",
			"ET": "Effective turns",
			"Suggestca": "Dynamic load(kg)",
			"Sload": "Static load(kg)",
			"NutOD": "Nut Dg6(mm)",
			"NutLen": "Nut length(mm)",
			"LifeCal": "Life calculate",
			"NutDynamic": "Nut dynamic load(kgf)",
			"Mrpm": "MeanRotation(rpm)",
			"Mload": "MeanLoad(kgf)",
			"SO": "Safe coefficient",
			"LifeP": "Life prediction(hr)",
			"LifeR": "Life result",
			"CS": "Chosen screw O.D.",
			"Drpm": "Danger RPM",
			"RpmR": "RPM result",
			"Pstep": "PreviousStep",
			"Nstep": "NextStep"
		}
	]
}